name: on-commit

on:
  push:
    branches:
      - feat/notifier

jobs:
  my-simple-job:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Notify
        run: |
        pip3 install pyTelegramBotAPI && cd chore && python3 tgNotifier.py
        
