name: on-commit

on:
  push:
    branches:
      - feat/notifier

jobs:
  my-simple-job:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:
      - name: Prerun
        run: apt-get update && apt-get upgrade && python3 -m pip install --upgrade pip setuptools wheel

      - name: Checkout
        uses: actions/checkout@v2

      - name: Notify
        run: cd chore && python3 -m pip install -r requirements.txt && python3 tgNotifier.py
        
